/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      screens: {
        sm: "480px",
        md: "768px",
        lg: "976px",
        xl: "1440px",
      },
      colors: {
        primary: "var(--color-primary)",
        secondary: "var(--color-secondary)",
        accent: "var(--color-accent)",
        mainBg: "var(--color-mainBg)",
        btnPrimary: "var(--color-btnPrimary)",
        btnTextPrimary: "var(--color-btnTextPrimary)",
        btnHoverPrimary: "var(--color-btnHoverPrimary)",
        btnSecondary: "var(--color-btnSecondary)",
        btnTextSecondary: "var(--color-btnTextSecondary)",
        btnHoverSecondary: "var(--color-btnHoverSecondary)",
        textPrimary: "var(--color-textPrimary)",
        textSecondary: "var(--color-textSecondary)",
        textInPrimary: "var(--color-textInPrimary)",
        sectionTitle: "var(--color-sectionTitle)",
        sectionSubtitle: "var(--color-sectionSubtitle)",
        navbarBg: "var(--color-navbarBg)",
        navbarText: "var(--color-navbarText)",
        navbarActive: "var(--color-navbarActive)",
        navbarBorder: "var(--color-navbarBorder)",
        bannerTextPrimary: "var(--color-bannerTextPrimary)",
        bannerTextSecondary: "var(--color-bannerTextSecondary)",
        cardBgPrimary: "var(--color-cardBgPrimary)",
        cardBgSecondary: "var(--color-cardBgSecondary)",
        cardTextPrimary: "var(--color-cardTextPrimary)",
        cardTextSecondary: "var(--color-cardTextSecondary)",
        cardBorder: "var(--color-cardBorder)",
        cardBorderHover: "var(--color-cardBorderHover)",
        footerBg: "var(--color-footerBg)",
        footerText: "var(--color-footerText)",
        footerTitle: "var(--color-footerTitle)",
        footerBorder: "var(--color-footerBorder)",
      },
    },
  },
  plugins: [],
};
